--Tables
Select Top 1 * from dbo.Dim_Customers
Select Top 1 * from dbo.Dim_Products
Select Top 1 * from dbo.Dim_Regions
Select Top 1 * from dbo.Dim_SalesTeams
Select Top 1 * from dbo.Dim_Store_location
Select Top 1 * from dbo.FactTable


--Descriptive Analysis:
--What is the total sales revenue for each sales channel?
SELECT "Sales Channel", SUM("Order Quantity" * "Unit Price") AS "Total Sales Revenue"
FROM dbo.FactTable
GROUP BY "Sales Channel"

-- How many products were sold in each region?
Select ds.Region, count(f.OrderNumber) 
From dbo.Dim_SalesTeams ds
Join  dbo.FactTable f
On ds._SalesTeamID = f._SalesTeamID
Group by ds.Region

--What is the average unit price for each product?
Select dp.[Product Name], AVG(f."Unit Price")
From dbo.Dim_Products dp
Join dbo.FactTable f
On dp._ProductID = f._ProductID
Group By dp.[Product Name]

--Which products have the highest unit cost
Select dp.[Product Name], Max(f."Unit Price") as Unit_Price
From dbo.Dim_Products dp
Join dbo.FactTable f
On dp._ProductID = f._ProductID
Group By dp.[Product Name]

--What is the total population and median household income for each state?
Select State, sum(Population) as Total_Population, avg("Median Income") as Average_median_income
from dbo.Dim_Store_location
Group By State






--Performance Analysis:
--What is the average order processing time (ProcuredDate to ShipDate) for each sales channel?
Select "Sales Channel", Avg(Datediff(DAY, ProcuredDate, ShipDate)) as Order_Processing_time
from dbo.FactTable
Group By "Sales Channel"

--Which sales team has the highest and lowest sales revenue?
WITH SalesTeamRevenue AS (
    SELECT ds.[Sales Team], SUM(f.[Order Quantity] * f.[Unit Price]) AS TotalSalesRevenue
    FROM dbo.Dim_SalesTeams ds
    JOIN dbo.FactTable f ON ds._SalesTeamID = f._SalesTeamID
    GROUP BY ds.[Sales Team]
)
SELECT [Sales Team], TotalSalesRevenue AS Highest_Sales_Revenue
FROM SalesTeamRevenue
WHERE TotalSalesRevenue = (SELECT MAX(TotalSalesRevenue) FROM SalesTeamRevenue)
UNION ALL
SELECT [Sales Team], TotalSalesRevenue AS Lowest_Sales_Revenue
FROM SalesTeamRevenue
WHERE TotalSalesRevenue = (SELECT MIN(TotalSalesRevenue) FROM SalesTeamRevenue)







--Customer Analysis:
--Who are the top 5 customers with the highest total purchase value?
Select Top 5 dc."Customer Names", SUM(f.[Order Quantity] * f.[Unit Price]) AS TotalSalesRevenue
from dbo.Dim_Customers dc
Join dbo.FactTable f
On dc._CustomerID = f._CustomerID
Group By dc.[Customer Names]
Order By TotalSalesRevenue desc

--What is the distribution of customer types (In-Store, Online, Distributor)?
SELECT "Sales Channel", Count(OrderNumber) AS "Total Customers"
FROM dbo.FactTable
GROUP BY "Sales Channel"

--Which customers have made the most repeat purchases?
Select dc.[Customer Names], COUNT(f.OrderNumber) As "Total Purchases"
from dbo.Dim_Customers dc
Join dbo.FactTable f
On dc._CustomerID = f._CustomerID
Group By dc.[Customer Names]
Order By "Total Purchases" desc






--Product Analysis:
--What are the best-selling products in each region?
Select dp.[Product Name], ds.Region, Count(f.OrderNumber) as OrderCount
From dbo.Dim_Products dp
Join dbo.FactTable f
On dp._ProductID = f._ProductID
Join dbo.Dim_SalesTeams ds
On f._SalesTeamID = ds._SalesTeamID
Group By dp.[Product Name], ds.Region
Order By ds.Region

--What is the total revenue generated by each product category?
Select dp.[Product Name], SUM(f.[Order Quantity] * f.[Unit Price]) AS TotalSalesRevenue
From dbo.Dim_Products dp
Join dbo.FactTable f 
On dp._ProductID = f._ProductID
Group By dp.[Product Name]






--Geospatial Analysis:
--Are there any relationships between store location attributes (e.g., population, household income) and sales revenue?
Select dms.State,  SUM(dms.Population) as Total_Population, SUM(dms.[Household Income]) as Total_Income, SUM(f.[Order Quantity] * f.[Unit Price]) AS TotalSalesRevenue
From dbo.Dim_Store_location dms
Join dbo.FactTable f On dms._StoreID = f._StoreID
Group By dms.State






--Time Series Analysis:
--How have sales trends evolved over time? (e.g., monthly or yearly sales trends)
Select YEAR(OrderDate) AS SalesYear, MONTH(OrderDate) AS SalesMonth, SUM("Order Quantity" * "Unit Price") AS YearlySales
From dbo.FactTable
Group By YEAR(OrderDate), MONTH(OrderDate)
Order By SalesYear, SalesMonth
